### ISSUE TITLE
After sign in it graph api only returns user name and id and not all the other info such as email, location

### ISSUE THREAD

**Issue by sandeeppujare** [puneetkay/Facebook-PHP-CodeIgniter#14]
After sign in it graph api only returns user name and id and not all the other info such as email, location etc...am i dong something wrong ?

**Comment by yeshwanthhooduku** [comment]
Any updates on above mentioned issues

**Comment by aaryadev** [comment]
If your don't wish to share info those ino will be returned null.
After 2015 April there was big change in security which allow user to choose what information they re sharing.

**Comment by mgjuhler** [comment]
I only get name and id, no email or anything else.. and it is even if the user has given the app access to it.

**Comment by aaryadev** [comment]
Update :
`	$user = $this->facebook->getUser();
		$user_profile = FALSE;
        if ($user) {
            try {
                $user_profile = $this->facebook->api('/me?fields=name,email');
            } catch (FacebookApiException $e) {
                $user = null;
            }}

						if(count($user_profile) == 3){
							$avatar='https://graph.facebook.com/'.$user_profile['id'].'/picture?type=large';
							$data=json_encode(array('fb'=>$user_profile));
							$this->user_model->sign_in($user_profile['email'],$user_profile['name'],$avatar,$data);
							redirect($this->base_url);
						}
`
Request email extra scope (/me?fields=name,email)

hope this will help you , its working for me . if email not found in response we can show error in view saying , you have denied permission to view email.
